alertmanager:
  config:
    global:
      resolve_timeout: 1m

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 2m
      receiver: 'default-receiver'
      routes:
        - receiver: 'slack-notifications'

    receivers:
      - name: 'default-receiver'
        webhook_configs:
          - url: 'http://alertmanager-service.monitoring.svc:9093'  # Example internal webhook

      - name: 'slack-notifications'
        slack_configs:
          - api_url: 'https://hooks.slack.com/services/xxxxxxxxxxxx/xxxxxxxxxxxx/xxxxxxxxxxx' #this must be changed in case you what to test it 
            channel: '#all-testalerts'
